name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: samuelcorreadossantos
        password: ${{ secrets.SML_POC_NETCORE_GITHUB_ACTIONS_DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: samuelcorreadossantos/netcore-poc-github-actions:${{ github.run_id }}
